### ISSUE TITLE
noqa in documentation

### ISSUE THREAD

**Issue by pagpires** [modernatx/seqlike#37]
Hi team, thanks for creating this tool, it looks really nice!  

Just a question regarding `#noqa: DAR201`: it's generated in the doc in quite a few places (e.g. https://modernatx.github.io/seqlike/reference/seqlike/#seqlike.SeqLike.SeqLike.__deepcopy__--noqa-dar101).  I've tested that it can successfully be ommited via wrapping with `<!--  -->` ([ref](https://github.com/terrencepreilly/darglint/issues/21#issuecomment-696423076)). Curious if the team likes the fix?   Happy to submit a MR.

**Comment by ericmjl** [comment]
@pagpires that is a good catch! We would love to have that as a fix. :smile:

**Comment by pagpires** [comment]
Cool, filed a PR [here](https://github.com/modernatx/seqlike/pull/38#issue-1085367927).  Let me know if you have any concern.

**Comment by ericmjl** [comment]
Closed by #38. Thank you, @pagpires!

**Comment by ericmjl** [comment]
@all-contributors please add @pagpires for documentation
