### ISSUE TITLE
Consider using version pins for mkdocs-material to avoid code-breaking

### ISSUE THREAD

**Issue by sugatoray** [modernatx/seqlike#39]
At times mkdocs-material changes quite a bit. I would suggest you to use pinned versions for `mkdocs-material` at least (since mkdocs-material will also install mkdocs and pymdownx and a few more extensions, that you would not need to pin versions for).

I am suggesting this from my experience. If you don't want to find your website suddenly not updating anymore, please consider doing this as early as possible.

https://github.com/modernatx/seqlike/blob/df1bacedbfa862e4f31253d3006078d43eead4fe/environment.yml#L31-L34

**Comment by ericmjl** [comment]
Good point, @sugatoray. Thanks for the suggestion here!

@all-contributors please add @sugatoray for infra and maintenance.
