### ISSUE TITLE
Dispatch based on SeqLikeType.__args__

### ISSUE THREAD

**Issue by ericmjl** [modernatx/seqlike#42]
Also a quick note: when dispatching for SeqLike, I guess we can use `SeqLikeType.__args__` as the type instead of hardcoding a list of potential types, otherwise it's hard to keep them consistent (since I saw there's a plan to include torch.tensor)

_Originally posted by @pagpires in https://github.com/modernatx/seqlike/issues/41#issuecomment-1000942209_

**Comment by ericmjl** [comment]
@pagpires do let us know if you'd like to make this happen! Happy to assign it to you.

**Comment by pagpires** [comment]
sure! happy to

**Comment by pagpires** [comment]
PR: https://github.com/modernatx/seqlike/pull/46
Note that the forward-ref should be removed or replaced (e.g. `"torch.tensor"` removed, `"np.ndarray"` replaced with the `np.ndarray`) to be compatible with dispatch.  I also found the circular dependency of SeqLike and SeqLikeType a bit confusing.  Let me know if I missed the context for this design or there's a better way.
