### ISSUE TITLE
Seek graphic design support

### ISSUE THREAD

**Issue by ericmjl** [modernatx/seqlike#5]
- Avatar for Moderna

(this one?) ![](https://pbs.twimg.com/profile_images/1410575625350488064/2ywfTawX_400x400.jpg)

- SeqLike logo (?)

**Comment by andrewgiessel** [comment]
Update:  have engaged designers.  Timeline is roughly EOM.

**Comment by ericmjl** [comment]
We have a logo now! 🎉
