### ISSUE TITLE
Prepending a string to a SeqLike

### ISSUE THREAD

**Issue by ndousis** [modernatx/seqlike#51]
Prepending a string to SeqLike results unexpectedly in an appended version:
```
In [1]: from seqlike import SeqLike

In [2]: "ACTG" + SeqLike("TTTT", "nt", id="test")
Out[2]: 
*** NT: SeqRecord(seq=Seq('TTTTACTG'), id='test', name='<unknown name>', description='<unknown description>', dbxrefs=[]) 
```
This should either (1) result in an error ("cannot prepend a string to a SeqLike"), or (2) yield a new SeqLike with the metadata of the parent SeqLike and the correctly-ordered sequence string ("ACTGTTTT").  If the latter, should this new SeqLike be renumbered?

**Comment by andrewgiessel** [comment]
I vote for an error that says something like "Addition is only defined for two SeqLikes"
