### ISSUE TITLE
Adding Damien Farrell as a contributor

### ISSUE THREAD

**Issue by ericmjl** [modernatx/seqlike#58]
As mentioned by @ndousis in an earlier email thread, some of @dmnfarrell's code made it into this library. We would like to acknowledge @dmnfarrell as a contributor in the codebase.

@dmnfarrell is this something you would be amenable to? I would essentially ask the all-contributors bot to add your contribution in.

**Comment by dmnfarrell** [comment]
Hi. Yes that's fine. Thanks. Which particular code was used out of interest?

**Comment by ericmjl** [comment]
I believe @ndousis has the details, though if my memory serves right, it was the bokeh plotting code for multiple sequence alignments. 

Thanks for getting back so fast, @dmnfarrell. I will be triggering the bits shortly.

**Comment by ndousis** [comment]
That's correct-- I used @dmnfarrell 's blog post as the basis for our interactive alignment viewer:
https://dmnfarrell.github.io/bioinformatics/bokeh-sequence-aligner

There are credits buried in the `view_alignment()` docstring, but my apologies for not raising this sooner when we published the seqlike library.

**Comment by ericmjl** [comment]
@dmnfarrell I've noted in our README that you are a valued contributor to SeqLike! :tada:
