### ISSUE TITLE
`molecule_type` annotation lost in translated-back-translated sequence

### ISSUE THREAD

**Issue by ndousis** [modernatx/seqlike#68]
When back-translating a translated sequence, the `molecule_type` SeqRecord annotation is lost, resulting in a `ValueError: Proteins cannot be translated!` error.  This manifests when trying to slice a translated-back-translated sequence, e.g.:
```python
>>> s = SeqLike("TTCGACACTGCA", "nt").aa().back_translate(codon_map=ecoli_codon_map)
>>> s[0:3]

ValueError                                Traceback (most recent call last)
File ~/dev/seqlike/seqlike/SeqLike.py:610, in SeqLike.__getitem__(self, index)
    609 try:
--> 610     _aa_record = _nt_record.translate(gap=gap_letter)
    611 except Exception as e:

File ~/opt/anaconda3/envs/seqlike-dev/lib/python3.9/site-packages/Bio/SeqRecord.py:1354, in SeqRecord.translate(self, table, stop_symbol, to_stop, cds, gap, id, name, description, features, annotations, letter_annotations, dbxrefs)
   1353 if "protein" == self.annotations.get("molecule_type", ""):
-> 1354     raise ValueError("Proteins cannot be translated!")
   1355 answer = SeqRecord(
   1356     self.seq.translate(
   1357         table=table, stop_symbol=stop_symbol, to_stop=to_stop, cds=cds, gap=gap
   1358     )
   1359 )

ValueError: Proteins cannot be translated!

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
Cell In[7], line 2
      1 s = SeqLike("TTCGACACTGCA", "nt").aa().back_translate(codon_map=ecoli_codon_map)
----> 2 s[0 : 3]

File ~/dev/seqlike/seqlike/SeqLike.py:612, in SeqLike.__getitem__(self, index)
    610     _aa_record = _nt_record.translate(gap=gap_letter)
    611 except Exception as e:
--> 612     warnings.warn(e)
    613 sliced = SeqLike(_nt_record, **seqlike_kwargs)
    614 sliced._aa_record = _aa_record

TypeError: expected string or bytes-like object
```

**Comment by andrewgiessel** [comment]
Thanks @ndousis 

I think there is a larger design question/issue here about tracking the seq_type of the SeqLike.  We're using self._type == 'AA' or 'NT' to check this inside of seqlike itself, and the molecule_type annotation seems like a redundant/parallel way of doing this.  The reason we didn't use this to begin with is that "molecule_type" is optional, but looking at the BioPython code, it's used in multiple locations and might come up in other contexts.   In this case it seems to be added when we call `.translate()`

```python
from seqlike import SeqLike, ntSeqLike, aaSeqLike
s = SeqLike('aaaccctttggg', seq_type='NT')
s_translated = s.translate()
a = SeqLike('aaaccctttggg', seq_type='AA')

# output: {}, {'molecule_type': 'protein'}, {}
s.annotations, s_translated.annotations, a.annotations
```

I see three paths:

1) Strip out the annotations from the sequence after we call `.translate()`. This is my preference as it's the simplest and most self consistent

2) Ensure complete consistency between these attributes.  The code in #69 is a bandaid that does this for a single state (a backtranslated sequence).  This is complicated.

3) Unify the way we track this, potentially by done by setting `annotations["molecule_type"]` in `self._aa_seqrecord` and `self._nt_seqrecord`, and changing `self._type` to a property that looks up these value in `self._seqrecord` (i.e. the current sequence representation) before returning "AA" or "NT".  The complication is that the valid BioPython annotation strings are "DNA", "RNA", or "protein".  To set this accurately, we'd need to know this in detail, which is tricky and potentially impossible to automatically do.  We don't distinguish between nucleotide forms.

**Comment by andrewgiessel** [comment]
Quick addition that we actually set the molecule type to "DNA" in `.translate()` before we call BioPython's translate but it doesn't seem required to translate a sequence.  As part of 1) above, we should consider removing that as well.  

Moreover, in `test_SeqLike_interconversion()` we use `assert_matched_properties()` which makes sure the keys in the annotations between two seqlikes match.  This specific check in this test only passes because the SeqLike we start with is initialized with extra, non-default annotation.  @ericmjl wrote the test, but I wrote the code in `seqlike.translate()`. Pretty sure he had to add that to make the tests pass, which seems like another bandaid to deal with inconsistent state.

**Comment by ndousis** [comment]
Thanks @andrewgiessel for pointing out that `molecule_type` is unnecessary.  Along the lines of 1) above, BioPython's`SeqRecord.translate()` [sets `annotations["molecule_type"]` to "protein"](https://github.com/biopython/biopython/blob/master/Bio/SeqRecord.py#L1391)
```python
        answer.annotations["molecule_type"] = "protein"
```
I just pushed 2a7eba5, which eliminates this annotation and also removes the other `molecule_type` bandaids.

**Comment by ericmjl** [comment]
I'm in favour of option 1 - simplification gives us a cleaner base to work with going forward.

**Comment by ndousis** [comment]
I made the revisions suggested by @andrewgiessel and pushed 08d38f6 and 0bf7385.
